/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package overwatchhelpertool;
import java.awt.event.*;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author Phillip
 */
public class Menu extends javax.swing.JPanel {
        private Player player;
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        createActionListeners();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPanes = new javax.swing.JTabbedPane();
        playerLogin1 = new overwatchhelpertool.PlayerLogin();
        playerMenu1 = new overwatchhelpertool.PlayerMenu();
        playerScheduleMenu1 = new overwatchhelpertool.PlayerScheduleMenu();
        teamMenu1 = new overwatchhelpertool.TeamMenu();

        setPreferredSize(new java.awt.Dimension(1000, 500));

        menuPanes.addTab("tab2", playerLogin1);
        menuPanes.addTab("tab2", playerMenu1);
        menuPanes.addTab("tab3", playerScheduleMenu1);
        menuPanes.addTab("tab4", teamMenu1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanes)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanes)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createActionListeners(){
        //create a action listener for login botted on login menu
        playerLogin1.loginBot.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent e){
            playerLogin1.loginCheck();                                        //check if login was correct
            
            if(playerLogin1.loginStatus){
            menuPanes.setSelectedIndex(1);                                 //change to player menu
            System.out.println(playerLogin1.givePlayer()+playerLogin1.givePass());
            player = new Player(playerLogin1.givePlayer(),playerLogin1.givePass());
            JOptionPane.showMessageDialog(null,"Login succesfull! welcome "+player.giveName());  //message on succesfull login
            
        }}});
        
        //for create schedule botten on player menu
        playerMenu1.scheduleCreate.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent e){
            menuPanes.setSelectedIndex(2);                                  //change to schedule creating window
        }});
        
        //for create schedule botten on player menu
        playerScheduleMenu1.finalBotten.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent e){
            player.buildSchedule(playerScheduleMenu1.save());
            player.saveUser();
            menuPanes.setSelectedIndex(1);                                  //change to user menu
        }});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane menuPanes;
    private overwatchhelpertool.PlayerLogin playerLogin1;
    private overwatchhelpertool.PlayerMenu playerMenu1;
    private overwatchhelpertool.PlayerScheduleMenu playerScheduleMenu1;
    private overwatchhelpertool.TeamMenu teamMenu1;
    // End of variables declaration//GEN-END:variables
}
